### ISSUE TITLE
Can the PowerShell requirement be made not mandatory?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [ebekker/letsencrypt-win#12]
Currently there seem to be a few issues related to powershell (permissions, 32bit vs 64-bit etc). Could this client be built just as .net console app?

**Comment by Lone-Coder** [comment]
This is a great idea. KISS

**Comment by Lone-Coder** [comment]
There's no reason a .net command line client couldn't have the same usage options as the main client here: https://letsencrypt.org/howitworks/

**Comment by Lone-Coder** [comment]
@ebekker If I scraped together a command line client would you accept the pull request?

**Comment by webprofusion-chrisc** [comment]
@lone-coder that's perhaps a big ask. Nobody will accept a pr before seeing the code :) you should go ahead and try it anyway. I was thinking I might try a GUI if I get time (big if!).

**Comment by ebekker** [comment]
Just clarify, the permissions and 32-bit vs. 64-bit issues are not specific to PowerShell.  The permission issue is due to not running in elevated (Admin) mode, and the same issue would be encountered by any client running on Windows.

The 32-bit issue is due to the fact that I'm using the OpenSSL library for all of the local CSR/private key/certificate management.  Since OpenSSL is a native library is "matters" which version you use so that the 32-bit/64-bit version of the PowerShell instance that hosts has to match.  Any client that goes this route will have similar issues -- you'll need to match the bitness of the client with the bitness of any native libraries that are referenced.

**Comment by ebekker** [comment]
So to address @Lone-Coder 's [comment](https://github.com/ebekker/letsencrypt-win/issues/12#issuecomment-153792258), I wanted to just give a little history -- back when I started playing with the idea of a native Windows client, I originally did want to stick to the same CLI interface as the official LE client, however, as I started on the PowerShell client it quickly became clear that doing so would have required a deviation from normal PS conventions and would look and behave unexpectedly to someone who is familiar with and uses PS on a regular basis.

So why did I choose to go with PS?  Well, frankly, at least to me, it seems like the completely obvious and natural choice for Windows.  PS is *the* official language for Windows administration going forward, that's been made very clear by Microsoft.  PS is also designed to make it easy to integrate and interoperate with other system components on the Windows platform, for example to talk to IIS.

And finally, one of the motivations for doing this project for me was that I had my own *itch to scratch*, and I wanted a way to make use of the LE/ACME project for my own use cases, and in my day job, PS is the primary automation tool so it was a natural fit.

NOW, having said all that -- I think it would be just great if someone wanted to write an alternative tool to the PS module.  This project is structured in layers, so the ACME client library is just a plain old .NET assembly, and anyone can take that and make any client they wan (CLI, WPF, ASP.NET, MVC, etc.).  The ACME client library just focuses on the ACME protocol, i.e. interacting with an ACME server, so any client that uses it will still need to deal with the persistence of state, configuration and interacting with local (or remote!) system components, which is what the PS module does.

@Lone-Coder, if you put something like this together, I'll be happy to take the PR, if it's *reasonable*.  In this scenario, having 2 (or more) clients that build on the same client library would only help to strengthen that common library across more scenarios.

**Comment by Lone-Coder** [comment]
@ebekker Thanks for the feedback. I agree that PS is a great tool and an awesome way to do this, and that a CLI client will be nice to have as well.

**Comment by Lone-Coder** [comment]
So here's how far I got today. I'm running into some trouble with the authorization. Is there some event I need to wait for before continuing after these ACME calls?

Calling into Microsoft.Web.Administration to get the IIS sites was easier than I thought it would be.

Could you take a look at the AuthorizeIdentifier method at the bottom of this and see what I'm doing wrong? If you'd like I can check it in somewhere so you can give it a try easier.

    using LetsEncrypt.ACME;
    using LetsEncrypt.ACME.JOSE;
    using Microsoft.Web.Administration;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;

    namespace letsencrypt
    {
        class Program
        {
            public static string BaseURI { get; set; } = "https://acme-staging.api.letsencrypt.org/";
            //public static string BaseURI { get; set; } = "https://acme-v01.api.letsencrypt.org/directory";

            static string UserAgent = "Let's Encrypt Windows Command Line Client";

            static bool PromptYesNo()
            {
                while (true)
                {
                    var response = Console.ReadKey(true);
                    if (response.Key == ConsoleKey.Y)
                        return true;
                    if (response.Key == ConsoleKey.N)
                        return false;
                    Console.WriteLine("Please press Y or N.");
                }
            }

            static void Main(string[] args)
            {
                Console.WriteLine(UserAgent);

                //var vaultPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "LetsEncrypt");
                //Console.WriteLine("Vault Path: " + vaultPath);

                Console.WriteLine($"ACME Server: {BaseURI}");

                using (var signer = new RS256Signer())
                {
                    signer.Init();

                    using (var client = new AcmeClient(new Uri(BaseURI), new AcmeServerDirectory(), signer))
                    {
                        client.Init();
                        Console.WriteLine("Getting AcmeServerDirectory");
                        client.GetDirectory(true);

                        //client.UserAgent = UserAgent;

                        Console.WriteLine("Calling Register");
                        var registration = client.Register(new string[] { });

                        Console.WriteLine($"Do you agree to {registration.TosLinkUri}? (Y/N)");
                        if (!PromptYesNo())
                            return;

                        Console.WriteLine("Updating Registration");
                        client.UpdateRegistration(true, true);

                        Console.WriteLine("Scanning IIS 7 Site Bindings for Hosts (Elevated Permissions Required)");
                        var hosts = GetHostNames();
                        foreach (var hostName in hosts)
                        {
                            Console.WriteLine($"  - {hostName}");
                        }

                        foreach (var hostName in hosts)
                        {
                            AuthorizeIdentifier(client, hostName.Host, hostName.PhysicalPath);
                        }

                        //_testAuthz_AcmeAuthzFile = $"{_baseLocalStore}\\TestAuthz.acmeAuthz";
                        //using (var fs = new FileStream(_testAuthz_AcmeAuthzFile, FileMode.Create))
                        //{
                        //    authzState.Save(fs);
                        //}
                    }
                }

    #if DEBUG
                Console.WriteLine("Press enter to continue.");
                Console.ReadLine();
    #endif
            }

            static List<SiteHost> GetHostNames()
            {
                var result = new List<SiteHost>();
                using (var iisManager = new ServerManager())
                {
                    foreach (var site in iisManager.Sites)
                    {
                        foreach (var binding in site.Bindings)
                        {
                            if (!String.IsNullOrEmpty(binding.Host))
                                result.Add(new SiteHost() { Host = binding.Host, PhysicalPath = site.Applications["/"].VirtualDirectories["/"].PhysicalPath });
                        }
                    }
                }
                return result;
            }

            static void AuthorizeIdentifier(AcmeClient client, string dnsIdentifier, string webRootPath)
            {
                Console.WriteLine($"Authorizing Identifier {dnsIdentifier}");
                var authzState = client.AuthorizeIdentifier(dnsIdentifier);

                Console.WriteLine("Getting challenge answer from ACME server.");
                var challenge = client.GenerateAuthorizeChallengeAnswer(authzState, AcmeProtocol.CHALLENGE_TYPE_HTTP);
                var answerPath = Path.Combine(webRootPath, challenge.ChallengeAnswer.Key);

                Console.WriteLine($"Writing challenge answer to {answerPath}");
                Directory.CreateDirectory(Path.GetDirectoryName(answerPath));
                File.WriteAllText(answerPath, challenge.ChallengeAnswer.Value);

                try
                {
                    Console.WriteLine("Submitting answer");
                    // This always throws throw new InvalidOperationException("challenge answer has not been generated"); because the authoState.Challenge list isn't changing for some reason
                    //client.SubmitAuthorizeChallengeAnswer(authzState, AcmeProtocol.CHALLENGE_TYPE_HTTP, true);

                    // so I pulled the core of SubmitAuthorizeChallengeAnswer into it's own method that I can call directly
                    client.SubmitAuthorizeChallengeAnswer(challenge, true);
                }
                finally
                {
                    Console.WriteLine("Deleting answer");
                    File.Delete(answerPath);
                }

                Console.WriteLine("Refreshing authorization");
                authzState = client.RefreshIdentifierAuthorization(authzState);

                // If I put a break point here, Status is invalid, otherwise it still shows as pending.

                Console.WriteLine($"Authorization RESULT: {authzState.Status}");
            }
        }
    }

**Comment by webprofusion-chrisc** [comment]
This is really cool, you'll probably need to have the status check be async so that it can poll for status a few times over a few seconds. The server probably takes an indeterminate amount of time to process the request (I imagine). Alternatively you may need a two step process so that you can do the result check some time later.

**Comment by ebekker** [comment]
@Lone-Coder, I created separate branch for the CLI client code (client-cli), you can fork the project and then do your development in that branch.  And I'll start pulling your changes in.

**Comment by webprofusion-chrisc** [comment]
Changed the title of the issue to more accurately reflect the sentiment that Powershell is cool but it would be nice to not require it.

As an aside, if nobody has already pointed it out - this project is amazing. I can't believe the amount of work that has been done and the level of detail that has been considered, it's astonishing. While I can see this particular client goes further than the basic ACME spec, I think the Vault concept for managing everything is brilliant.

I have made a start on a GUI (just for fun) that works with the Vault (read only so far), there is scope for further separation in the code (the File Vault requires a powershell session) but that's minor.

**Comment by ebekker** [comment]
In my experience, there's only a small delay when you ask the LE stage server to complete and identifier authorization challenge, and there's no delay when you request a cert to be issued (the cert is immediately available when you submit your cert request for a previously-authorized identifier).

You can see how the code in the ```AcmeClientUnitTests.cs``` class in the ```LetsEncrypt.ACME-test``` project completes each task.  (Note, this is not really a set of unit tests, but more of a set of integration tests with the LE stage server, as the individual tests are serially dependent and have to be run in a certain order.)

**Comment by ebekker** [comment]
@Lone-Coder, I committed a first set of changes based on your code sample above plus some tweaks just to make sure the code compiles.  I didn't actually test the client yet, because I'm still setting up the local IIS on my development workstation.

**Comment by Lone-Coder** [comment]
Thanks for setting up the branch.

I just tried pushing to it but got this message. Can you give me rights to push to that branch or do I need to mess with making my own fork?

    git.exe push --progress "origin" client-cli:client-cli
    
    remote: Permission to ebekker/letsencrypt-win.git denied to Lone-Coder.
    fatal: unable to access 'https://github.com/ebekker/letsencrypt-win/': The requested URL returned error: 403

**Comment by Lone-Coder** [comment]
Look Ma! I can fork!

https://github.com/Lone-Coder/letsencrypt-win/tree/client-cli

Sorry. I'm pretty green with the git-fu.

**Comment by lennybacon** [comment]
@Lone-Coder +1 LOL

**Comment by Lone-Coder** [comment]
So I made some really good progress. It's fully passing auth for my and am getting certs down.

Here's a build if anyone would like to try it:
https://github.com/Lone-Coder/letsencrypt-win/raw/client-cli/letsencrypt-win/LetsEncrypt.ACME.CLI/LetsEncrypt%20Windows%20Client%20Build.zip

Here's the things it's missing:

**Comment by Lone-Coder** [comment]
So I'm stuck here. Can't generate a Pfx file so so far I've not been able to get anything to import into IIS.

    CsrHelper.Crt.ConvertToPfx(keyPemFile, crtPemFile, irsPemFile, crtPfxFile, FileMode.Create);

What is irsPemFile and where am I suppose to get it? Seems like the code for it is only in UpdateCertificate and should maybe be moved up higher to the LetsEncrypt.ACME library.

**Comment by Lone-Coder** [comment]
Is there a way to get IIS to load the certs without a .pfx file? Seems I've got all the other files for the cert.

**Comment by Lone-Coder** [comment]
Here's the current code for the client: https://github.com/Lone-Coder/letsencrypt-win/blob/client-cli/letsencrypt-win/LetsEncrypt.ACME.CLI/Program.cs

**Comment by lennybacon** [comment]
In general it would be a good idea to generate a private key and the PKCS#10 using the Windows built in COM APIs. Have a look here http://blogs.msdn.com/b/alejacma/archive/2008/09/05/how-to-create-a-certificate-request-with-certenroll-and-net-c.aspx?PageIndex=5

When the certificate is returned from the CA it can just be installed to the certificate store.

IIS can then juts use it.

**Comment by ebekker** [comment]
@lennybacon, I agree that using a native Windows technology would be a preferred approach, and in fact I was looking at the native CertEnroll API stuff very early on.  One of the problems I ran into was that I needed to support a few different formats to make everything work (e.g. raw DER formats for the ACME protocol exchanges, PKCS 12  (.PFX) for import into the Windows Cert store, PEM format for [various](http://nginx.org/en/docs/windows.html) - [alternative](https://httpd.apache.org/docs/2.2/platform/windows.html) - [services](https://tomcat.apache.org/tomcat-7.0-doc/windows-service-howto.html) on Windows), and CertEnroll doesn't offer good support for importing/exporting into formats that are not part of the native environment.

So when I looked around for such alternatives, the only common solution I always ran into was OpenSSL, so I figured, let's just start with that, because in theory it already supports every use case.  And that is what I've found.

The challenge I've had with OpenSSL has actually been related to the .NET interaction with the native library, and so my thinking right now is that I'm going to sever that tight integration and stick a generic interface to those PKI Cert-related calls.  And then the default implementation will actually be a CLI-call interface into an OpenSSL console client, instead of an assembly reference.

This will address the 32-bit/64-bit issue.  It will also decouple the OpenSSL implementation, so anyone can substitute a different version of the binary (e.g. LibreSSL), as long as it is CLI-compatible.

The other advantage is that the interface will allow you to substitute and entirely different implementation, so if you can satisfy all the required calls using CertEnroll, then so be it, it will be an easy drop-in.

**Comment by ebekker** [comment]
@Lone-Coder, the `irsPemFile` parameter, is actually **isrPemFile** and it's the *Issuer Certificate* in PEM format.

To construct the PKCS12 file, you need the private key and the public cert of your target Identifier, as well as the public cert of the issuer that issued your cert.

**Comment by lennybacon** [comment]
@ebekker If we could define an interface for different formats (e.g. provider model) for "(e.g. raw DER formats for the ACME protocol exchanges, PKCS 12 (.PFX) for import into the Windows Cert store, PEM format for various - alternative - services on Windows)" I would be able to contribute the *native* windows implementation.

**Comment by Lone-Coder** [comment]
@ebekker So there's this code in UpdateCertificate.cs. Is this getting the isrPemFile, and should I move some of it up to the LetsEncrypt.ACME project so that it can be reused?

                                var tmp = Path.GetTempFileName();
                                try
                                {
                                    using (var web = new WebClient())
                                    {
                                        if (v.Proxy != null)
                                            web.Proxy = v.Proxy.GetWebProxy();

                                        var uri = new Uri(new Uri(v.BaseURI), upLink.Uri);
                                        web.DownloadFile(uri, tmp);
                                    }

                                    var cacert = new X509Certificate2(tmp);
                                    var sernum = cacert.GetSerialNumberString();
                                    var tprint = cacert.Thumbprint;
                                    var sigalg = cacert.SignatureAlgorithm?.FriendlyName;
                                    var sigval = cacert.GetCertHashString();

                                    if (v.IssuerCertificates == null)
                                        v.IssuerCertificates = new OrderedNameMap<IssuerCertificateInfo>();
                                    if (!v.IssuerCertificates.ContainsKey(sernum))
                                    {
                                        var cacertDerFile = $"ca-{sernum}-crt.der";
                                        var cacertPemFile = $"ca-{sernum}-crt.pem";

                                        if (Repeat || !File.Exists(cacertDerFile))
                                            File.Copy(tmp, cacertDerFile, true);
                                        if (Repeat || !File.Exists(cacertPemFile))
                                            CsrHelper.Crt.ConvertDerToPem(cacertDerFile, cacertPemFile);

                                        v.IssuerCertificates[sernum] = new IssuerCertificateInfo
                                        {
                                            SerialNumber = sernum,
                                            Thumbprint  = tprint,
                                            SignatureAlgorithm = sigalg,
                                            Signature = sigval,
                                            CrtDerFile = cacertDerFile,
                                            CrtPemFile = cacertPemFile,
                                        };
                                    }

                                    ci.IssuerSerialNumber = sernum;
                                }
                                finally
                                {
                                    if (File.Exists(tmp))
                                        File.Delete(tmp);
                                }

**Comment by Lone-Coder** [comment]
I just got the pfx file working.

**Comment by Lone-Coder** [comment]
Finally got the cert installed on my server! Huzzah!

Just pushed a new build at https://github.com/Lone-Coder/letsencrypt-win/raw/client-cli/letsencrypt-win/LetsEncrypt.ACME.CLI/LetsEncrypt%20Windows%20Client%20Build.zip that should work fairly well.

@ebekker Can you take a look at the pull request I sent over? Seems like the AppVeyor isn't configured right for my fork.

Also, @ebekker how should I go about saving the registration? Does it need to be in an encrypted vault?

Also, should I delete the answer files off the web server if the auth passes?

**Comment by ebekker** [comment]
A part of the the client-side state for the registration is the private key used for signing requests, that piece is *sensitive* and should be encrypted or guarded some how.  In the latest changes for Vault, I still have a few pieces that need to be broken out into their own distinct assets, such as this "Signer Key" and I also need to go back and flag all the sensitive assets.

**Comment by Lone-Coder** [comment]
> A part of the the client-side state for the registration is the private key used for signing requests, that piece is sensitive and should be encrypted or guarded some how. In the latest changes for Vault, I still have a few pieces that need to be broken out into their own distinct assets, such as this "Signer Key" and I also need to go back and flag all the sensitive assets.

Do you know what the linux python client does with the registration key? Is it just stored to disk or do they have it in a secure store somewhere?

**Comment by ebekker** [comment]
The LE [reference implementation client](https://github.com/letsencrypt/letsencrypt) uses a server-wide folder to store all of their configuration and operational state (`/etc/letsencrypt`) and within this folder, they use file system permissions to restrict access to root.

My intention is basically to so the same thing with the default file-based Vault provider, that is, use file system ACLs to restrict write of anything and reading of secrets to the local Administrators group.

The one additional safe-guard I may introduce is applying [EFS](https://technet.microsoft.com/en-us/library/cc700811.aspx) to the secret-holding files -- but the challenge there is in an environment where you may have multiple admin-level users managing certs, you would need to ensure that all eligible users are explicitly granted encryption key access to the necessary files.  Whereas ACLs can grant read/write access to a group of users (such as local or domain admins), EFS encryption key access has to be assigned explicitly to individuals, and that can break things unexpectedly, so it will pby be an option via configuration rather than the default behavior.

Other Vault providers, such as [this one](../7) would use comparable safe-guards that are more native to that storage mechanism.

**Comment by Lone-Coder** [comment]
Here's a new release and build location of my simple windows CLI client. This new release will save and re-use registration.

https://mob0.com/Lets%20Encrypt%20Windows%20CLI%200.5.zip

**Comment by Lone-Coder** [comment]
I'm starting to think the CLI client should be a separate github project to avoid confusion and so that I don't have to wait for pull requests into a separate branch. It needs separate documentation and support anyways. I'm going to close my pull request and start setting up a different project.

**Comment by ebekker** [comment]
That's cool, I hope you didn't just give up on me because I was taking so long on the PR -- I'm addressing a couple issues related to licensing and trademarks with LE before I start taking any outside contributions.

**Comment by Lone-Coder** [comment]
Oh, did they not like us using the LE name?

**Comment by Lone-Coder** [comment]
Here's the location of my separate CLI client project:

https://github.com/Lone-Coder/letsencrypt-win-simple

**Comment by ebekker** [comment]
It wasn't them, it was me.  I started thinking about embedding the `letsencrypt` name in things like file paths and configuration elements and such, and it occurred I really needed to make sure there wouldn't be legal or technical challenges.

LE hasn't yet established an official trademark usage policy. And if they ever decide to come up with their own official Windows client or even adapt the Python client to windows, their could be name conflicts in file path or registry keys.  So it's actually safer for me to get a jump start on this issue now before it gets to far along.

**Comment by Lone-Coder** [comment]
My simple client now handles automatic renewals, so I'm calling this release 1.0.

Please check it out at https://github.com/Lone-Coder/letsencrypt-win-simple

**Comment by ebekker** [comment]
Looks great!

**Comment by ebekker** [comment]
I'm going to close out this issue as your client clearly provides a good alternative to the POSH module.  I'm planning on wrapping up the ACME library part into its own nuget package shortly, so soon you can sever the code dependency altogether and just reference it as a nuget package.
