### ISSUE TITLE
Submit-ACMECertificate reporting "The system cannot find the file specified"

### ISSUE THREAD

**Issue by DanielBrownAU** [ebekker/letsencrypt-win#21]
Great work with this, looking forward to giving it a good try with my sites.

So far, I've gotten as far as Submit-ACMECertificate, where it reports:

Submit-ACMECertificate : The system cannot find the file specified.
At line:1 char:1
+ Submit-ACMECertificate -Ref cert2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMECertificate], CryptographicException
    + FullyQualifiedErrorId : System.Security.Cryptography.CryptographicException,LetsEncrypt.ACME.POSH.SubmitCertific
   ate

I am running Powershell as Admin, x86, tho the gotcha is, it is Windows 2016 Preview 3.

I've tried copying the files to the operating directory, checked logs/event logs and cannot seem to find much sorry.

Just using the example on the usage wiki with domains & paths changed.

Running Update-ACMECertificate produces:

PS C:\Vault> Update-ACMECertificate -Ref cert2
Update-ACMECertificate : Certificate has not been submitted yet; cannot update status
At line:1 char:1
+ Update-ACMECertificate -Ref cert2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-ACMECertificate], Exception
    + FullyQualifiedErrorId : System.Exception,LetsEncrypt.ACME.POSH.UpdateCertificate

Not sure what is going on / next steps sorry.

Any help would be greatly appreciated.

**Comment by DanielBrownAU** [comment]
So have busted open the code.....

Line 138 in  letsencrypt-win/letsencrypt-win/LetsEncrypt.ACME.POSH/SubmitCertificate.cs

var crt = new X509Certificate2(crtDerFile);

This is the line causing the problem, for some reason, its unable to find the crtDerFile file, which is populated with ba61baea-2eca-49f3-9fdf-54d6fa551805-crt.der

This file, is also located in the vault, in C:\vault\66-CRTDR.

Solution: Have hard coded the file path and what do you know, it has worked! -- How does one get the location of the folder? Is there a method already in place for this?

**Comment by ebekker** [comment]
Ah, good catch!  I missed this *direct file reference* when I refactored the code to use Vault assets.

I'll push out a fix shortly.

**Comment by DanielBrownAU** [comment]
Cool!

Also, When exporting with:

Get-ACMECertificate -Ref cert9 `
    -ExportKeyPEM cert9-key.pem `
    -ExportCsrPEM cert9-csr.pem `
    -ExportCertificatePEM cert9-crt.pem `
    -ExportCertificateDER cert9-crt.der `
    -ExportPkcs12 cert9-all.pfx


I had to copy the files manually into the C:\Vault\45-KEYPM folder.

They where all these, just in various other folders, which was coming back as not being able to be found. I suspect much of the same is happening here too.

**Comment by ebekker** [comment]
@DanielBrownAU, the two issues you found were fixed and committed to master, thanks!

**Comment by DanielBrownAU** [comment]
Great! Ill re-download the master and give it a test on the win10 server sometime today.

Thanks again!

**Comment by DanielBrownAU** [comment]
Hi Eugene

I have just downloaded and succesfully tested the changes on my Windows 2016 Server. Am able to genereate the ceritificate and export them without issue.

Thanks again!

DB

**Comment by ebekker** [comment]
Cool, thanks for testing.  On Win2016, you're running with the current/preview version of PowerShell v5, correct?

Also, did you do your test from start to finish, i.e. starting with creating a registration, then authorizing an Identifer (DNS), then requesting a cert, or did you start the test from one of the middle steps?

**Comment by DanielBrownAU** [comment]
Hi Eugene,

Ran that test from start to finish, all worked with creating the vault, validating the website and getting the certificate created as well as exported.

I've stopped short on the IIS install script (with this post, as there is another issue with that one).

But Yes, Windows Server 2016, IT Preview 3, PowerShell v5 (x86).


--
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10514  0

---

Cheers,

DB

**Comment by ebekker** [comment]
The issue with IIS install (I'm guessing) that you're running into is pby related to the 32/64 bit issue, which is one of the things I'm working on right now.  Since you have to run the PS session in 32-bit, on a 64-bit machine, you won't be able to make use of the PS cmdlets for installing the cert to IIS directly.

I'm addressing that issue right now and will soon eliminate the 32-bit requirement.

Thanks again, for testing.
