### ISSUE TITLE
Bug: GenerateCsr

### ISSUE THREAD

**Issue by matbech** [ebekker/letsencrypt-win#27]
The GenerateCsr function looks completely wrong:
https://github.com/ebekker/letsencrypt-win/blob/master/letsencrypt-win/LetsEncrypt.ACME/PKI/CsrHelper.cs#L73

For example:
            if (!string.IsNullOrEmpty(csrDetails.Country            /**/)) xn.Common = csrDetails.Country;          // C;

should be:
            if (!string.IsNullOrEmpty(csrDetails.Country            /**/)) xn.Country = csrDetails.Country;          // C;

etc

**Comment by webprofusion-chrisc** [comment]
So by completely wrong, you mean there's a typo?

**Comment by ebekker** [comment]
Ouch, yep, about a dozen of the x509 name components are messed up, only the common name is correct.

I'm fixing it along with the changes I'm making for Cert management in #16.

**Comment by ebekker** [comment]
Unfortunately, it's a bit more than just a typo, but still very young code -- thanks for all the testing!
