### ISSUE TITLE
Complete-ACMEIdentifier is not recognized as the name of a cmdlet, function etc.

### ISSUE THREAD

**Issue by josephcooney** [ebekker/letsencrypt-win#4]
Following along with the example in the Readme.md, I received an error when I attempted to execute 

Complete-ACMEIdentifier -Ref dns1 -Challenge simpleHttp -ProviderConfig s3HttpProvider

The error message was: "The term 'Complete-ACMEIdentifier' is not recognized as the name of a cmdlet, function , script file, or operable program"

Looking at the source code I was unable to find this function.

**Comment by KurtHofman** [comment]
Same problem here.

mkdir c:\Vault
cd c:\Vault
[Environment]::CurrentDirectory = (Get-Location -PSProvider FileSystem).ProviderPath 
Import-Module C:\letsencrypt-win\bin\ACMEPowerShell
Initialize-ACMEVault -BaseURI https://acme-staging.api.letsencrypt.org/
New-ACMERegistration -Contacts mailto:xxx@xxx
Update-ACMERegistration -AcceptTOS
New-ACMEIdentifier -Dns xxx.xx -Alias dns1 -Label "DNS asci.be" -Memo "xxx.xx"
New-ACMEProviderConfig -DnsProvider Manual       -Alias manualDnsProvider
New-ACMEProviderConfig -DnsProvider AwsRoute53   -Alias r53DnsProvider
New-ACMEProviderConfig -WebServerProvider Manual -Alias manualHttpProvider
New-ACMEProviderConfig -WebServerProvider AwsS3  -Alias s3HttpProvider
Get-ACMEIdentifier -Ref dns1
Complete-ACMEIdentifier -Ref dns1 -Challenge simpleHttp -ProviderConfig s3HttpProvider

Complete-ACMEIdentifier : The term 'Complete-ACMEIdentifier' is not recognized as the name of a cmdlet, function, scrip
t file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
 and try again.
At line:1 char:1
+ Complete-ACMEIdentifier -Ref dns1 -Challenge simpleHttp -ProviderConfig s3HttpPr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Complete-ACMEIdentifier:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ebekker** [comment]
My mistake, the correct cmdlet name is ``Complete-ACMEChallenge``, I've corrected the RE

**Comment by yomexzo** [comment]
@ebekker, It turns out issue persists.

```
PS C:\> Complete-ACMEChallenge
Complete-ACMEChallenge : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Complete-ACMEChallenge
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Complete-ACMEChallenge], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,ACMESharp.POSH.CompleteChallenge
```

**Comment by yomexzo** [comment]
@ebekker,

I don't know if this is a separate issue, but this happens

```
PS C:\> Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebS
iteRef = 'ref' }
Complete-ACMEChallenge : The given key was not present in the dictionary.
At line:1 char:1
+ Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler iis -Handler ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,ACMESharp.POSH.CompleteChallenge
```

**Comment by ebekker** [comment]
@yomexzo, that's most likely from reference name being undefined, it's complaining that it can find the reference in the Vault.  Is `dns1` defined before hand?  Is your Web Site in IIS actually called `ref`?

**Comment by yomexzo** [comment]
lol, No. I replaced the actual name with `ref` before pasting.

I figured it out eventually actually.

The alias (dns2 ....) parameter from the previous steps confused me. I thought it referred to other domain names like you'd want to add to the CSR e.g www.example.com to example.com. So i was using dns1 instead of dns2 which was the alias.

Thanks @ebekker ...

**Comment by ebekker** [comment]
@yomexzo, sounds good, glad it worked out!
