### ISSUE TITLE
Complete-ACMEChallenge : Access to the path 'C:\inetpub.asci.be\supportroot' is denied.

### ISSUE THREAD

**Issue by KurtHofman** [ebekker/letsencrypt-win#5]
I'm quit new with all this stuff so I guess I'm doing some thins wrong.
No I get an access denied for my webcontent-folder.

manualHttpProvider:
{
    "Provider": {
        "$type": "LetsEncrypt.ACME.WebServer.ManualWebServerProvider, LetsEncrypt.ACME",
        "FilePath": "C:\\inetpub.asci.be\\supportroot\\"
    }
}

Script :
mkdir c:\Vault
cd c:\Vault
[Environment]::CurrentDirectory = (Get-Location -PSProvider FileSystem).ProviderPath 
Import-Module C:\letsencrypt-win\bin\ACMEPowerShell
Initialize-ACMEVault -BaseURI https://acme-staging.api.letsencrypt.org/
New-ACMERegistration -Contacts mailto:kh@asci.be
Update-ACMERegistration -AcceptTOS
New-ACMEIdentifier -Dns asci.be -Alias dns1 -Label "DNS asci.be" -Memo "asci.be"
New-ACMEProviderConfig -DnsProvider Manual       -Alias manualDnsProvider
New-ACMEProviderConfig -DnsProvider AwsRoute53   -Alias r53DnsProvider
New-ACMEProviderConfig -WebServerProvider Manual -Alias manualHttpProvider
New-ACMEProviderConfig -WebServerProvider AwsS3  -Alias s3HttpProvider
Edit-ACMEProviderConfig -List
Edit-ACMEProviderConfig -Ref manualHttpProvider
Complete-ACMEChallenge -Ref dns1 -Challenge simpleHttp -ProviderConfig manualHttpProvider

Error: 
PS C:\vault> Complete-ACMEChallenge -Ref dns1 -Challenge simpleHttp -ProviderConfig manualHttpProvider
Complete-ACMEChallenge : Could not find a part of the path 'C:\inetpub.asci.be\supportroot\'.
At line:1 char:1
+ Complete-ACMEChallenge -Ref dns1 -Challenge simpleHttp -ProviderConfig manualHtt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,LetsEncrypt.ACME.POSH.CompleteChallenge

**Comment by ebekker** [comment]
The exception is actually a ``DirectoryNoFoundException`` so can you confirm the path ``C:\inetpub.asci.be\supportroot\`` exists on the host you're running the PS cmdlets from?

**Comment by KurtHofman** [comment]
Yes, the folder exists. when I create a file in PS-shell en that folder the file is being created without a problem.

**Comment by ebekker** [comment]
A couple things, can you see what the PS process CWD is, just print out ``[Environment]::CurrentDirectory`` and see if it matches your current PS CWD.  This may have something to do with the issue reported in #3 and I committed a change just recently to correct that behavior.

The other thing, can you see if there are any more details on the error, such as an inner exception?  Just after you get the error, you can print that with ``$Error[0].Exception.InnerExcepetion``

**Comment by ebekker** [comment]
Also, are you by any chance able to run a PS session while debugging the module code?  If so you can see where in the code it's throwing the exception and see some more details.

**Comment by KurtHofman** [comment]
I did some tests :

PS C:\Vault> [Environment]::CurrentDirectory
C:\Vault
PS C:\Vault> Complete-ACMEChallenge -Ref dns1 -Challenge simpleHttp -ProviderConfig manualHttpProvider
Complete-ACMEChallenge : Access to the path 'C:\inetpub.asci.be\supportroot' is denied.
At line:1 char:1
+ Complete-ACMEChallenge -Ref dns1 -Challenge simpleHttp -ProviderConfig manualHtt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,LetsEncrypt.ACME.POSH.CompleteChallenge
PS C:\Vault> $Error[0].Exception.InnerExcepetion
PS C:\Vault> 

I'll try to debug

**Comment by ebekker** [comment]
A couple more thoughts.

The inetpub folder path usually requires administrative access to update.  Can you try using a different path that you know is not restricted, just to test and see if the challenge response file can be generated and saved?

Also, what "Execution Policy" do you have configured by default for your PowerShell environment on this machine?  Depending on the policy, it may restrict PowerShell modules or scripts for writing to, or accessing resources using elevated privileges.  As a test, you can try to run the following in a single PS session, this will require PS to prompt you to run any unsigned or untrusted code:

```Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force```

**Comment by KurtHofman** [comment]
I adjusted the rights and altered the json-file and now it works !
Now I get 
Submit-ACMEChallenge : The term 'Submit-ACMEChallenge' is not recognized as the name of a cmdlet, function, script file
, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and t
ry again.

{
    "Provider": {
        "$type": "LetsEncrypt.ACME.WebServer.ManualWebServerProvider, LetsEncrypt.ACME",
        "FilePath": "C:\\inetpub.asci.be\\updateroot\\letsencrypt"
    }
}

**Comment by KurtHofman** [comment]
Submit-ACMEChallenges instead of Submit-ACMEChallenge works !

**Comment by KurtHofman** [comment]
Submit-ACMEChallenges instead of Submit-ACMEChallenge works !

**Comment by KurtHofman** [comment]
I just tested on another instance and I've to adjust the security on that folder so that .\Users have full rights.
